name: 'Appian Promote'
description: 'Import an Appian package into a target environment'
inputs:
  base-url:
    description: 'Base URL of Appian environment'
    required: true
  api-key:
    description: 'Appian API key'
    required: true
  package-path:
    description: 'Path to package zip file'
    required: true
  poll-timeout-sec:
    description: 'Polling timeout in seconds'
    required: false
  poll-interval-sec:
    description: 'Polling interval in seconds'
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        CMD=("${{ github.workspace }}/scripts/appian_promote.sh" \
          --base-url "${{ inputs.base-url }}" \
          --api-key "${{ inputs.api-key }}" \
          --package-path "${{ inputs.package-path }}")
        [[ -n "${{ inputs.poll-timeout-sec }}" ]] && CMD+=(--poll-timeout-sec "${{ inputs['poll-timeout-sec'] }}")
        [[ -n "${{ inputs.poll-interval-sec }}" ]] && CMD+=(--poll-interval-sec "${{ inputs['poll-interval-sec'] }}")
        "${CMD[@]}"

