name: appian-export (MVP)
description: Exporta recurso Appian (app o package) y descarga los artefactos asociados

inputs:
  env:
    description: Entorno Appian (dev|qa|prod|demo)
    required: true
  deploy_kind:
    description: Tipo de recurso a exportar (app|package)
    required: true
  app_uuid:
    description: UUID de la aplicación origen
    required: true
  package_name:
    description: Nombre del paquete (para deploy_kind=package)
    required: false
    default: ''
  app_name:
    description: Nombre amigable de la aplicación (opcional, para naming)
    required: false
    default: ''

outputs:
  artifact_path:
    description: Ruta relativa del ZIP exportado
    value: ${{ steps.process.outputs.artifact_path }}
  artifact_dir:
    description: Directorio relativo que contiene los artefactos
    value: ${{ steps.process.outputs.artifact_dir }}
  manifest_path:
    description: Ruta relativa al manifest con metadatos de la exportación
    value: ${{ steps.process.outputs.manifest_path }}
  raw_response_path:
    description: Ruta relativa al archivo con la respuesta cruda de Appian
    value: ${{ steps.process.outputs.raw_response_path }}
  deployment_uuid:
    description: UUID del deployment de export en Appian
    value: ${{ steps.process.outputs.deployment_uuid }}
  deployment_status:
    description: Estado final reportado por Appian para la exportación
    value: ${{ steps.process.outputs.deployment_status }}
  artifact_name:
    description: Nombre del artifact subido
    value: ${{ steps.metadata.outputs.artifact_name }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Resolver API key
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/../appian-promote/scripts/resolve_api_key.py" \
          --env-name "${{ inputs.env }}" \
          --env-var-name "APPIAN_API_KEY" \
          --skip-if-present

    - name: Resolver APPIAN_BASE_URL desde config del Core
      shell: bash
      run: |
        set -euo pipefail
        file="${{ github.action_path }}/../_config/appian_base_urls.env"
        env_in='${{ inputs.env }}'
        env_lc="${env_in,,}"
        case "$env_lc" in
          dev)   val=$(grep -E '^DEV='  "$file" | sed 's/^DEV=//') ;;
          qa)    val=$(grep -E '^QA='   "$file" | sed 's/^QA=//') ;;
          prod)  val=$(grep -E '^PROD=' "$file" | sed 's/^PROD=//') ;;
          demo)  val=$(grep -E '^DEMO=' "$file" | sed 's/^DEMO=//') ;;
          *) echo "::error::env inválido: $env_in"; exit 1 ;;
        esac
        echo "APPIAN_BASE_URL=$val" >> "$GITHUB_ENV"
        if [ -z "${val:-}" ]; then
          echo "::error::APPIAN_BASE_URL vacío para '$env_in'"; exit 1
        fi

    - id: resource_init
      name: Resolver recurso a exportar
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/resource_resolver.py" \
          --deploy-kind "${{ inputs.deploy_kind }}" \
          --app-uuid "${{ inputs.app_uuid }}" \
          --package-name "${{ inputs.package_name }}" \
          --app-name "${{ inputs.app_name }}"

    - id: package
      if: ${{ steps.resource_init.outputs.needs_lookup == 'true' }}
      name: Resolver UUID del paquete
      uses: ./.github/actions/appian-resolve-package
      with:
        env_name: ${{ inputs.env }}
        app_uuid: ${{ inputs.app_uuid }}
        package_name: ${{ inputs.package_name }}

    - id: resource
      name: Finalizar datos del recurso
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/resource_resolver.py" \
          --deploy-kind "${{ inputs.deploy_kind }}" \
          --app-uuid "${{ inputs.app_uuid }}" \
          --package-name "${{ inputs.package_name }}" \
          --package-uuid "${{ steps.package.outputs.package_uuid }}" \
          --app-name "${{ inputs.app_name }}"

    - id: cli
      name: Ejecutar export
      shell: bash
      env:
        APPIAN_API_KEY: ${{ env.APPIAN_API_KEY }}
        APPIAN_BASE_URL: ${{ env.APPIAN_BASE_URL }}
      run: |
        set -euo pipefail
        if [ -n "${APPIAN_API_KEY:-}" ]; then
          echo "::add-mask::${APPIAN_API_KEY}"
        fi
        out_json="$RUNNER_TEMP/appian-export.json"
        python "${{ github.action_path }}/appian_cli.py" export \
          --base-url "$APPIAN_BASE_URL" \
          --api-key "$APPIAN_API_KEY" \
          --kind "${{ steps.resource.outputs.resource_kind }}" \
          --rid "${{ steps.resource.outputs.resource_id }}" \
          --name "${{ steps.resource.outputs.display_name }}" \
          --outdir artifacts > "$out_json"
        echo "payload_path=$out_json" >> "$GITHUB_OUTPUT"

    - id: process
      name: Procesar artefactos
      shell: bash
      env:
        PAYLOAD_PATH: ${{ steps.cli.outputs.payload_path }}
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/export_postprocess.py" \
          --payload-file "${PAYLOAD_PATH}"

    - id: metadata
      name: Calcular nombre de artifact
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/artifact_name.py" \
          --artifact-path "${{ steps.process.outputs.artifact_path }}" \
          --deploy-kind "${{ steps.resource.outputs.resource_kind }}" \
          --resource-id "${{ steps.resource.outputs.resource_id }}" \
          --package-name "${{ inputs.package_name }}" \
          --app-name "${{ inputs.app_name }}"

    - name: Subir paquete exportado (ZIP)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.artifact_name }}
        path: ${{ steps.process.outputs.artifact_path }}
        if-no-files-found: error
        retention-days: 5

    - name: Subir metadata de exportación
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.artifact_name }}-meta
        path: |
          ${{ steps.process.outputs.manifest_path }}
          ${{ steps.process.outputs.raw_response_path }}
        if-no-files-found: error
        retention-days: 5

    - name: Subir scripts de base de datos
      if: ${{ steps.process.outputs.artifact_dir != '' && hashFiles(format('{0}/db-scripts/**', steps.process.outputs.artifact_dir)) != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.artifact_name }}-db-scripts
        path: ${{ steps.process.outputs.artifact_dir }}/db-scripts
        if-no-files-found: error
        retention-days: 5

    - name: Subir customization file
      if: ${{ steps.process.outputs.artifact_dir != '' && hashFiles(format('{0}/customization/customization.properties', steps.process.outputs.artifact_dir)) != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.artifact_name }}-customization
        path: ${{ steps.process.outputs.artifact_dir }}/customization/customization.properties
        if-no-files-found: error
        retention-days: 5

    - name: Subir customization template
      if: ${{ steps.process.outputs.artifact_dir != '' && hashFiles(format('{0}/customization/customization-template.properties', steps.process.outputs.artifact_dir)) != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.artifact_name }}-customization-template
        path: ${{ steps.process.outputs.artifact_dir }}/customization/customization-template.properties
        if-no-files-found: error
        retention-days: 5

    - name: Subir plugins ZIP
      if: ${{ steps.process.outputs.artifact_dir != '' && hashFiles(format('{0}/plugins/plugins.zip', steps.process.outputs.artifact_dir)) != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.artifact_name }}-plugins
        path: ${{ steps.process.outputs.artifact_dir }}/plugins/plugins.zip
        if-no-files-found: error
        retention-days: 5
