name: appian-export (MVP)
description: Exporta recurso Appian (app o package) y genera un ZIP simulado

inputs:
  env_name:
    description: Entorno Appian (solo para logging)
    required: true
  resource_kind:
    description: Tipo de recurso a exportar (app|application|package)
    required: true
  resource_id:
    description: UUID del recurso (app_uuid o package_uuid)
    required: true
  display_name:
    description: Nombre amigable para nombrar el archivo (opcional)
    required: false
    default: ''
  dry_run:
    description: Si es true, no llama APIs y genera archivo simulado
    required: false
    default: 'false'

outputs:
  artifact_path:
    description: Ruta del artefacto exportado (zip)
    value: ${{ steps.make.outputs.artifact_path }}
  artifact_dir:
    description: Carpeta local que contiene los artefactos descargados
    value: ${{ steps.make.outputs.artifact_dir }}
  database_scripts:
    description: JSON con metadata de scripts de base de datos descargados
    value: ${{ steps.make.outputs.database_scripts }}
  plugins_zip:
    description: Ruta del ZIP de plugins exportado (si aplica)
    value: ${{ steps.make.outputs.plugins_zip }}
  customization_file:
    description: Ruta del archivo de personalización exportado (si aplica)
    value: ${{ steps.make.outputs.customization_file }}
  customization_template:
    description: Ruta del template de personalización exportado (si aplica)
    value: ${{ steps.make.outputs.customization_template }}
  downloaded_files:
    description: JSON con todas las rutas descargadas por la acción
    value: ${{ steps.make.outputs.downloaded_files }}
  deployment_uuid:
    description: UUID del deployment de export en Appian
    value: ${{ steps.make.outputs.deployment_uuid }}
  deployment_status:
    description: Estado final reportado por Appian para la exportación
    value: ${{ steps.make.outputs.deployment_status }}
  raw_response:
    description: JSON crudo devuelto por Appian al completar la exportación
    value: ${{ steps.make.outputs.raw_response }}

runs:
  using: composite
  steps:
    - name: Resolver APPIAN_BASE_URL desde config del Core
      shell: bash
      run: |
        set -euo pipefail
        file="${{ github.action_path }}/../_config/appian_base_urls.env"
        env_lc='${{ inputs.env_name }}'; env_lc="${env_lc,,}"
        case "$env_lc" in
          dev)   val=$(grep -E '^DEV='  "$file" | sed 's/^DEV=//') ;;
          qa)    val=$(grep -E '^QA='   "$file" | sed 's/^QA=//') ;;
          prod)  val=$(grep -E '^PROD=' "$file" | sed 's/^PROD=//') ;;
          demo)  val=$(grep -E '^DEMO=' "$file" | sed 's/^DEMO=//') ;;
          *) echo "::error::env_name inválido: $env_lc"; exit 1 ;;
        esac
        echo "APPIAN_BASE_URL=$val" >> "$GITHUB_ENV"
        if [ -z "${val:-}" ]; then
          echo "::error::APPIAN_BASE_URL vacío para '$env_lc'"; exit 1
        fi
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - id: make
      shell: bash
      env:
        APPIAN_API_KEY: ${{ env.APPIAN_API_KEY }}
        APPIAN_BASE_URL: ${{ env.APPIAN_BASE_URL }}
      run: |
        set -euo pipefail
        echo "::add-mask::${APPIAN_API_KEY:-}"
        payload=$(python "${{ github.action_path }}/appian_cli.py" export \
          --base-url "$APPIAN_BASE_URL" \
          --api-key "$APPIAN_API_KEY" \
          --kind "${{ inputs.resource_kind }}" \
          --rid "${{ inputs.resource_id }}" \
          --name "${{ inputs.display_name }}" \
          --outdir artifacts \
          $([ "${{ inputs.dry_run }}" = "true" ] && echo --dry-run || true))
        payload=$(echo "$payload" | tail -n 1 | tr -d '\r')
        tmp_payload=$(mktemp)
        printf '%s' "$payload" > "$tmp_payload"
        export PAYLOAD_FILE="$tmp_payload"
        python <<'PY'
import json
import os
from pathlib import Path

payload_path = Path(os.environ['PAYLOAD_FILE'])
data = json.loads(payload_path.read_text())

output_path = Path(os.environ['GITHUB_OUTPUT'])
with output_path.open('a', encoding='utf-8') as fh:
    fh.write(f"artifact_path={data['package_path']}\n")
    fh.write(f"artifact_dir={data['artifact_dir']}\n")
    fh.write(f"database_scripts={json.dumps(data['database_scripts'])}\n")
    fh.write(f"plugins_zip={data['plugins_zip']}\n")
    fh.write(f"customization_file={data['customization_file']}\n")
    fh.write(f"customization_template={data['customization_template']}\n")
    fh.write(f"downloaded_files={json.dumps(data['downloaded_files'])}\n")
    fh.write(f"deployment_uuid={data['deployment_uuid']}\n")
    fh.write(f"deployment_status={data['deployment_status']}\n")
    fh.write(f"raw_response={json.dumps(data['raw_response'])}\n")
PY
        rm -f "$tmp_payload"
