name: appian-export (MVP)
description: Exporta recurso Appian (app o package) y descarga los artefactos asociados

inputs:
  env:
    description: Entorno Appian (dev|qa|prod|demo)
    required: true
  deploy_kind:
    description: Tipo de recurso a exportar (app|package)
    required: true
  app_uuid:
    description: UUID de la aplicación origen
    required: true
  package_name:
    description: Nombre del paquete (para deploy_kind=package)
    required: false
    default: ''
  app_name:
    description: Nombre amigable de la aplicación (opcional, para naming)
    required: false
    default: ''

outputs:
  artifact_path:
    description: Ruta relativa del ZIP exportado
    value: ${{ steps.export.outputs.artifact_path }}
  artifact_dir:
    description: Directorio relativo que contiene los artefactos
    value: ${{ steps.export.outputs.artifact_dir }}
  manifest_path:
    description: Ruta relativa al manifest con metadatos de la exportación
    value: ${{ steps.export.outputs.manifest_path }}
  raw_response_path:
    description: Ruta relativa al archivo con la respuesta cruda de Appian
    value: ${{ steps.export.outputs.raw_response_path }}
  deployment_uuid:
    description: UUID del deployment de export en Appian
    value: ${{ steps.export.outputs.deployment_uuid }}
  deployment_status:
    description: Estado final reportado por Appian para la exportación
    value: ${{ steps.export.outputs.deployment_status }}
  artifact_name:
    description: Nombre del artifact subido
    value: ${{ steps.metadata.outputs.artifact_name }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Resolver API key
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/../appian-promote/scripts/resolve_api_key.py" \
          --env-name "${{ inputs.env }}" \
          --env-var-name "APPIAN_API_KEY" \
          --skip-if-present

    - name: Resolver APPIAN_BASE_URL desde config del Core
      shell: bash
      run: |
        set -euo pipefail
        file="${{ github.action_path }}/../_config/appian_base_urls.env"
        env_in='${{ inputs.env }}'
        env_lc="${env_in,,}"
        case "$env_lc" in
          dev)   val=$(grep -E '^DEV='  "$file" | sed 's/^DEV=//') ;;
          qa)    val=$(grep -E '^QA='   "$file" | sed 's/^QA=//') ;;
          prod)  val=$(grep -E '^PROD=' "$file" | sed 's/^PROD=//') ;;
          demo)  val=$(grep -E '^DEMO=' "$file" | sed 's/^DEMO=//') ;;
          *) echo "::error::env inválido: $env_in"; exit 1 ;;
        esac
        echo "APPIAN_BASE_URL=$val" >> "$GITHUB_ENV"
        if [ -z "${val:-}" ]; then
          echo "::error::APPIAN_BASE_URL vacío para '$env_in'"; exit 1
        fi

    - id: resource_init
      name: Resolver recurso a exportar
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/resource_resolver.py" \
          --deploy-kind "${{ inputs.deploy_kind }}" \
          --app-uuid "${{ inputs.app_uuid }}" \
          --package-name "${{ inputs.package_name }}" \
          --app-name "${{ inputs.app_name }}"

    - id: package
      if: ${{ steps.resource_init.outputs.needs_lookup == 'true' }}
      name: Resolver UUID del paquete
      uses: ./.github/actions/appian-resolve-package
      with:
        env_name: ${{ inputs.env }}
        app_uuid: ${{ inputs.app_uuid }}
        package_name: ${{ inputs.package_name }}

    - id: resource
      name: Finalizar datos del recurso
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/resource_resolver.py" \
          --deploy-kind "${{ inputs.deploy_kind }}" \
          --app-uuid "${{ inputs.app_uuid }}" \
          --package-name "${{ inputs.package_name }}" \
          --package-uuid "${{ steps.package.outputs.package_uuid }}" \
          --app-name "${{ inputs.app_name }}"

    - id: export
      name: Ejecutar export
      shell: bash
      env:
        APPIAN_API_KEY: ${{ env.APPIAN_API_KEY }}
        APPIAN_BASE_URL: ${{ env.APPIAN_BASE_URL }}
      run: |
        set -euo pipefail
        if [ -n "${APPIAN_API_KEY:-}" ]; then
          echo "::add-mask::${APPIAN_API_KEY}"
        fi
        payload=$(python "${{ github.action_path }}/appian_cli.py" export \
          --base-url "$APPIAN_BASE_URL" \
          --api-key "$APPIAN_API_KEY" \
          --kind "${{ steps.resource.outputs.resource_kind }}" \
          --rid "${{ steps.resource.outputs.resource_id }}" \
          --name "${{ steps.resource.outputs.display_name }}" \
          --outdir artifacts)
        payload=$(echo "$payload" | tail -n 1 | tr -d '\r')
        tmp_payload=$(mktemp)
        printf '%s' "$payload" > "$tmp_payload"
        export PAYLOAD_FILE="$tmp_payload"
        python <<'PY'
        import json
        import os
        import sys
        from pathlib import Path

        payload_path = Path(os.environ['PAYLOAD_FILE'])
        data = json.loads(payload_path.read_text())

        output_path = Path(os.environ['GITHUB_OUTPUT'])
        workspace = Path(os.environ['GITHUB_WORKSPACE']).resolve()

        def fail(msg: str) -> None:
            sys.stderr.write(f"::error::{msg}\n")
            sys.exit(1)

        def to_rel(path: str) -> str:
            if not path:
                return ""
            p = Path(path).resolve()
            try:
                return str(p.relative_to(workspace))
            except ValueError:
                return str(p)

        package_path = data.get('package_path', '')
        if not package_path:
            fail("appian_cli.py export no devolvió 'package_path'")
        package_file = Path(package_path)
        if not package_file.exists():
            fail(f"No se encontró ZIP exportado en '{package_path}'")

        artifact_dir_raw = data.get('artifact_dir', '')
        if not artifact_dir_raw:
            fail("appian_cli.py export no devolvió 'artifact_dir'")
        artifact_dir = Path(artifact_dir_raw)
        if not artifact_dir.exists():
            fail(f"El directorio de artefactos '{artifact_dir_raw}' no existe")

        manifest_path = artifact_dir / 'export-manifest.json'
        raw_response_path = artifact_dir / 'export-response.json'

        manifest_data = {
            'artifact_path': to_rel(str(package_file)),
            'artifact_dir': to_rel(str(artifact_dir)),
            'deployment_uuid': data.get('deployment_uuid', ''),
            'deployment_status': data.get('deployment_status', ''),
            'downloaded_files': [to_rel(p) for p in data.get('downloaded_files', [])],
            'database_scripts': [
                {
                    **entry,
                    'path': to_rel(entry.get('path', '')),
                }
                for entry in data.get('database_scripts', [])
                if isinstance(entry, dict)
            ],
            'plugins_zip': to_rel(data.get('plugins_zip', '')),
            'customization_file': to_rel(data.get('customization_file', '')),
            'customization_template': to_rel(data.get('customization_template', '')),
        }

        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(
            json.dumps(manifest_data, ensure_ascii=False, indent=2), encoding='utf-8'
        )
        raw_response_path.write_text(
            json.dumps(data.get('raw_response', {}), ensure_ascii=False, indent=2),
            encoding='utf-8',
        )

        with output_path.open('a', encoding='utf-8') as fh:
            fh.write(f"artifact_path={manifest_data['artifact_path']}\n")
            fh.write(f"artifact_dir={manifest_data['artifact_dir']}\n")
            fh.write(f"manifest_path={to_rel(str(manifest_path))}\n")
            fh.write(f"raw_response_path={to_rel(str(raw_response_path))}\n")
            fh.write(f"deployment_uuid={data.get('deployment_uuid', '')}\n")
            fh.write(f"deployment_status={data.get('deployment_status', '')}\n")
        PY
        rm -f "$tmp_payload"

    - id: metadata
      name: Calcular nombre de artifact
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/scripts/artifact_name.py" \
          --artifact-path "${{ steps.export.outputs.artifact_path }}" \
          --deploy-kind "${{ steps.resource.outputs.resource_kind }}" \
          --resource-id "${{ steps.resource.outputs.resource_id }}" \
          --package-name "${{ inputs.package_name }}" \
          --app-name "${{ inputs.app_name }}"
