name: 'Appian Export'
description: 'Export an Appian application or package'
inputs:
  base-url:
    description: 'Base URL of Appian environment'
    required: true
  api-key:
    description: 'Appian API key'
    required: true
  export-type:
    description: 'application or package'
    required: true
  uuid:
    description: 'UUID of the application or package'
    required: true
  name:
    description: 'Optional export name'
    required: false
  description:
    description: 'Optional export description'
    required: false
  poll-timeout-sec:
    description: 'Polling timeout in seconds'
    required: false
  poll-interval-sec:
    description: 'Polling interval in seconds'
    required: false
  download-out:
    description: 'Directory to download package artifacts'
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        CMD=("${{ github.workspace }}/scripts/appian_export.sh" \
          --base-url "${{ inputs.base-url }}" \
          --api-key "${{ inputs.api-key }}" \
          --export-type "${{ inputs.export-type }}" \
          --uuid "${{ inputs.uuid }}")
        [[ -n "${{ inputs.name }}" ]] && CMD+=(--name "${{ inputs.name }}")
        [[ -n "${{ inputs.description }}" ]] && CMD+=(--description "${{ inputs.description }}")
        [[ -n "${{ inputs.poll-timeout-sec }}" ]] && CMD+=(--poll-timeout-sec "${{ inputs['poll-timeout-sec'] }}")
        [[ -n "${{ inputs.poll-interval-sec }}" ]] && CMD+=(--poll-interval-sec "${{ inputs['poll-interval-sec'] }}")
        [[ -n "${{ inputs['download-out'] }}" ]] && CMD+=(--download-out "${{ inputs['download-out'] }}")
        "${CMD[@]}"

