name: appian-promote
description: Orquesta la inspección e importación de un paquete Appian

inputs:
  source_env:
    description: Entorno origen (para logging)
    required: true
  target_env:
    description: Entorno destino (para logging)
    required: true
  package_path:
    description: Ruta del paquete a importar (zip)
    required: true
  icf_path:
    description: Ruta al ICF (import customization file) opcional
    required: false
  data_source:
    description: Nombre o UUID del data source para ejecutar scripts de base de datos (opcional)
    required: false
  db_scripts_path:
    description: Directorio con scripts SQL/DDL a ejecutar (opcional)
    required: false

outputs:
  deployment_status:
    description: Estado final reportado por Appian
    value: ${{ steps.import.outputs.deployment_status }}
  deployment_uuid:
    description: UUID del deployment en Appian
    value: ${{ steps.import.outputs.deployment_uuid }}

runs:
  using: composite
  steps:
    - name: Resolver APPIAN_BASE_URL desde config del Core
      shell: bash
      run: |
        set -euo pipefail
        file="${{ github.action_path }}/../_config/appian_base_urls.env"
        env_lc='${{ inputs.target_env }}'; env_lc="${env_lc,,}"
        case "$env_lc" in
          dev)   val=$(grep -E '^DEV='  "$file" | sed 's/^DEV=//') ;;
          qa)    val=$(grep -E '^QA='   "$file" | sed 's/^QA=//') ;;
          prod)  val=$(grep -E '^PROD=' "$file" | sed 's/^PROD=//') ;;
          demo)  val=$(grep -E '^DEMO=' "$file" | sed 's/^DEMO=//') ;;
          *) echo "::error::target_env inválido: $env_lc"; exit 1 ;;
        esac
        echo "APPIAN_BASE_URL=$val" >> "$GITHUB_ENV"
        if [ -z "${val:-}" ]; then
          echo "::error::APPIAN_BASE_URL vacío para '$env_lc'"; exit 1
        fi
    - name: Resolver configuración de promote (enable_inspection)
      shell: bash
      run: |
        set -euo pipefail
        # Permitir override por env ya definido en el workflow
        if [ -z "${APPIAN_PROMOTE_ENABLE_INSPECTION:-}" ]; then
          conf="${{ github.action_path }}/../_config/appian_promote.env"
          if [ -f "$conf" ]; then
            val=$(grep -E '^APPIAN_PROMOTE_ENABLE_INSPECTION=' "$conf" | sed 's/^APPIAN_PROMOTE_ENABLE_INSPECTION=//')
          else
            val=""
          fi
          val="${val:-true}"
          echo "APPIAN_PROMOTE_ENABLE_INSPECTION=$val" >> "$GITHUB_ENV"
        else
          echo "APPIAN_PROMOTE_ENABLE_INSPECTION=${APPIAN_PROMOTE_ENABLE_INSPECTION}" >> "$GITHUB_ENV"
        fi
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Inspect package
      if: env.APPIAN_PROMOTE_ENABLE_INSPECTION == 'true'
      shell: bash
      env:
        APPIAN_API_KEY_TARGET: ${{ env.APPIAN_API_KEY_TARGET }}
        APPIAN_BASE_URL: ${{ env.APPIAN_BASE_URL }}
      run: |
        set -euo pipefail
        echo "::add-mask::${APPIAN_API_KEY_TARGET:-}"
        cmd=(
          python "${{ github.action_path }}/appian_cli.py" inspect
          --base-url "$APPIAN_BASE_URL"
          --api-key "$APPIAN_API_KEY_TARGET"
          --package-path "${{ inputs.package_path }}"
        )
        if [ -n "${{ inputs.icf_path }}" ]; then
          cmd+=(--icf-path "${{ inputs.icf_path }}")
        fi
        "${cmd[@]}"

    - name: Import package
      id: import
      shell: bash
      env:
        APPIAN_API_KEY_TARGET: ${{ env.APPIAN_API_KEY_TARGET }}
        APPIAN_BASE_URL: ${{ env.APPIAN_BASE_URL }}
      run: |
        set -euo pipefail
        echo "::add-mask::${APPIAN_API_KEY_TARGET:-}"
        out_json="$RUNNER_TEMP/appian-promote-import.json"
        cmd=(
          python "${{ github.action_path }}/appian_cli.py" import
          --base-url "$APPIAN_BASE_URL"
          --api-key "$APPIAN_API_KEY_TARGET"
          --package-path "${{ inputs.package_path }}"
          --json-output "$out_json"
        )
        if [ -n "${{ inputs.icf_path }}" ]; then
          cmd+=(--icf-path "${{ inputs.icf_path }}")
        fi
        if [ -n "${{ inputs.data_source }}" ]; then
          cmd+=(--data-source "${{ inputs.data_source }}")
        fi
        if [ -n "${{ inputs.db_scripts_path }}" ]; then
          cmd+=(--db-scripts-dir "${{ inputs.db_scripts_path }}")
        fi
        "${cmd[@]}"
        status=""
        uuid=""
        if [ -f "$out_json" ]; then
          readarray -t parsed < <(OUT_JSON="$out_json" python - <<'PY'
        import json, os, sys
        path = os.environ.get("OUT_JSON", "")
        data = {}
        if path:
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    data = json.load(fh)
            except Exception:
                data = {}
        for key in ("status", "uuid"):
            sys.stdout.write(str(data.get(key, "")) + "\n")
        PY
        )
                  if [ "${#parsed[@]}" -ge 1 ]; then status="${parsed[0]}"; fi
                  if [ "${#parsed[@]}" -ge 2 ]; then uuid="${parsed[1]}"; fi
                fi
                {
                  echo "deployment_status=$status"
                  echo "deployment_uuid=$uuid"
                } >> "$GITHUB_OUTPUT"
