name: 'Resolve Appian Package'
description: 'Resolve package UUID for an application'
inputs:
  base-url:
    description: 'Base URL of Appian environment'
    required: true
  api-key:
    description: 'Appian API key'
    required: true
  app-uuid:
    description: 'UUID of the application'
    required: true
  package-name:
    description: 'Optional package name to match'
    required: false
outputs:
  package-uuid:
    description: 'UUID of resolved package'
    value: ${{ steps.resolve.outputs.uuid }}
runs:
  using: 'composite'
  steps:
    - id: resolve
      shell: bash
      run: |
        CMD=("${{ github.workspace }}/scripts/appian_resolve_package.sh" \
          --base-url "${{ inputs.base-url }}" \
          --api-key "${{ inputs.api-key }}" \
          --app-uuid "${{ inputs['app-uuid'] }}")
        [[ -n "${{ inputs['package-name'] }}" ]] && CMD+=(--package-name "${{ inputs['package-name'] }}")
        UUID=$("${CMD[@]}")
        echo "uuid=$UUID" >> "$GITHUB_OUTPUT"
